### ISSUE TITLE
PINYIN_KEEP_PUNCTUATION选项不起作用

### ISSUE THREAD

**Issue by adamwuyu** [overtrue/pinyin#134]
加上PINYIN_KEEP_PUNCTUATION选项后，不报错，但也不会输出标点符号，比如书名号。convert函数和sentence函数都是这样。

**Comment by overtrue** [comment]
只会保留这些：https://github.com/overtrue/pinyin/blob/master/src/Pinyin.php#L45

**Comment by yaqianghan** [comment]
> 只会保留这些：https://github.com/overtrue/pinyin/blob/master/src/Pinyin.php#L45

这些标点符号可以自定义吗  ？  比如➕
