### ISSUE TITLE
中文全角顿号、会导至php直接奔溃

### ISSUE THREAD

**Issue by steve3d** [overtrue/pinyin#146]
找了许久才找到这个问题, 只要用 `$pinyin->abbr('中、文')` 就会导至php 直接崩溃.

奇怪的是, 这个问题在mac下面的php 7.3.10/11下面没有, 我的Linux服务器上的7.3.10/11只要有顿号, php直接奔溃, 什么错误提示都没有.

**Comment by overtrue** [comment]
这么神奇？

Steve Yin <notifications@github.com>于2019年10月28日 周一下午11:54写道：

**Comment by steve3d** [comment]
<img width="597" alt="截屏2019-10-2907 57 19" src="https://user-images.githubusercontent.com/670687/67726739-c9eb0c00-fa21-11e9-921d-5ddf3707b283.png">

刚才在虚拟机上试了一下, 一样的结果

**Comment by xiaodit** [comment]
Docker PHP 7.3.10
没发现有这问题

**Comment by overtrue** [comment]
@steve3d 这个问题貌似是 psysh 的锅，你可以升级一下试试

**Comment by steve3d** [comment]
@overtrue 才试了一下, 已经是psysh 0.9.9 最新了, 还是一样, 有顿号就直接退.

ubuntu 18.04 , 用的 https://launchpad.net/~ondrej/+archive/ubuntu/php 这里的php
```
PHP 7.3.11-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:23:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by steve3d** [comment]
@xiaodit 我在mac下面也没这问题呢...

**Comment by hermithacker** [comment]
同样遇到了
带顿号就会
Segmentation fault

**Comment by fasthold** [comment]
通用 ubuntu 18.04,  php 7.3, apache 运行
带有中文顿号就崩溃，现在临时解决办法是先把顿号替换为空

**Comment by overtrue** [comment]
无法复现，各位先自行替换后使用。
