### ISSUE TITLE
php7.3和php7.4环境下,3.x系列和4.x系列都是行为不一致.这是

### ISSUE THREAD

**Issue by xltxlm** [overtrue/pinyin#147]
这是不然我用php7.4版本啊

$a = "php73";
 $b = (new Pinyin())->sentence($a);
//php73下 输出 php73
//php74下 输出 php

具体验证代码
https://github.com/gitdebugdemo/pinyin/blob/php74-4.0.5/tests/Test.php

验证集成环境:
php73-ok
https://github.com/gitdebugdemo/pinyin/tree/php73-4.0.5  
php74-不ok.数字73被删除了.
https://github.com/gitdebugdemo/pinyin/tree/php74-4.0.5 

![WX20191219-153946](https://user-images.githubusercontent.com/7278002/71154378-5f628980-2276-11ea-8f7f-dbb842095258.png)

**Comment by xltxlm** [comment]
补充一个3.x系列在php7.4下不正确的行为

7.3正确
https://github.com/gitdebugdemo/pinyin/tree/php73-3.0.6
7.4 不正确
https://github.com/gitdebugdemo/pinyin/tree/php74-3.0.6

![WX20191219-160835](https://user-images.githubusercontent.com/7278002/71156056-24faeb80-227a-11ea-8e9c-32e7d8214bb3.png)

**Comment by mikeyzm** [comment]
应该是 7.4 下的 bug: https://bugs.php.net/bug.php?id=79233

https://github.com/overtrue/pinyin/blob/94fdb3ea6eca5677afd9548111d95bedcd5a4086/src/Pinyin.php#L306

将 `\p{N}` 改为 `0-9` 可匹配阿拉伯数字。

**Comment by overtrue** [comment]
@mikeyzm 感谢提醒！
@xltxlm 再试试新版

**Comment by xltxlm** [comment]
感谢！ 4.0.x版本在 php7.3 和 php7.4上的行为是一致的了。
