### ISSUE TITLE
希望选项可以使用多项

### ISSUE THREAD

**Issue by zizhuxuaner** [overtrue/pinyin#157]
希望选项可以使用多项，比如：PINYIN_KEEP_NUMBER 使用的同时 我还想用PINYIN_KEEP_ENGLISH PINYIN_KEEP_PUNCTUATION 诸如此类  该如何实现

**Comment by overtrue** [comment]
文档里记得写了例子吧

**Comment by overtrue** [comment]
选项1 | 选项2 | 选项3

**Comment by zizhuxuaner** [comment]
> 选项1 | 选项2 | 选项3

谢谢 没仔细看 现在找到了

**Comment by shiny** [comment]
> 选项1 | 选项2 | 选项3

建议增加姓名选项，例如"曾"字，作为姓名 应该优先是 zeng “曾志伟”，作为普通句子时优先为 ceng “曾经”
