### ISSUE TITLE
字母和数字连在一起的情况下的返回值

### ISSUE THREAD

**Issue by censhen** [overtrue/pinyin#16]
当字母和数字连一起的情况下，数字变成了：\\
传入: aaaa1234
> 输出: a\\

如果传入aaaa_1234
> 输出：aaaa_

我的设置是
Pinyin::set('delimiter', '');
Pinyin::set('accent', false);

想问一下，第一种情况只保留了一个字母还加上了双斜线？

**Comment by overtrue** [comment]
@censhen 我排查一下

**Comment by overtrue** [comment]
@censhen 搞定了，不好意思最近一直忙没来得及照顾它。

**Comment by censhen** [comment]
OK, 谢谢
