### ISSUE TITLE
旅行 的旅字拼音应该是lv

### ISSUE THREAD

**Issue by 2dYm** [overtrue/pinyin#165]
$pinyin->convert('带着希望去旅行，比到达终点更美好');
// ["dai", "zhe", "xi", "wang", "qu", "lyu", "xing", "bi", "dao", "da", "zhong", "dian", "geng", "mei", "hao"]

**Comment by almostless** [comment]
PINYIN_UMLAUT_V | 使用 v 代替 yu, 例如：吕 lyu 将会转为 lv
