### ISSUE TITLE
语句中带英文字母的转化为空

### ISSUE THREAD

**Issue by bojo123** [overtrue/pinyin#169]
语句中带英文字母的转化为空，这种中英文混写或者是英文的场景还是很多的

**Comment by overtrue** [comment]
https://github.com/overtrue/pinyin/blob/master/tests/AbstractDictLoaderTestCase.php#L202 这种？

**Comment by overtrue** [comment]
或者这种？https://github.com/overtrue/pinyin/blob/master/tests/AbstractDictLoaderTestCase.php#L73
