### ISSUE TITLE
如何获取包含数字/英文/中文的首字母

### ISSUE THREAD

**Issue by cwwjsyc** [overtrue/pinyin#171]
需求：
text="沃尔沃XC60运动版"；

这种如何获取到：abbr="WEWXC60YDB";
试了$pinyin->abbr($text, \PINYIN_KEEP_NUMBER | \PINYIN_KEEP_ENGLISH)；只能不包含数字/英文的一种；

**Comment by overtrue** [comment]
https://github.com/overtrue/pinyin/releases/tag/4.0.7
