### ISSUE TITLE
名字“乐慧英”，拼音是lehuiying，而不是yuehuiying

### ISSUE THREAD

**Issue by albin504** [overtrue/pinyin#181]
$result = $pinyin->name('乐慧英');
print_r($result);
Array
(
    [0] => yue
    [1] => hui
    [2] => ying
)

应该是le，而不是yue

**Comment by overtrue** [comment]
https://www.zdic.net/hans/%E4%B9%90
https://baike.baidu.com/item/%E4%B9%90%E5%A7%93/8974427
http://www.cnbjx.com/xingshi/le_1577.html

看了一下，其实这个姓两个读音都有，从起源占比来讲，yue反而更多一些，这边是否有其它资料来展示他们的使用率？

**Comment by albin504** [comment]
@overtrue 谢谢回复！
确实，查了资料，两种发音都有。
类似有多音字的情况，上面的api，把两种拼音都返回，是否更合适一些？

另外一个问题，麻烦大佬也回复下哦。
https://github.com/overtrue/pinyin/issues/144

漯河这个词的拼音，和CC-CEDICT库中的发音不一致。
想问下，是哪里出问题了？

**Comment by overtrue** [comment]
@albin504 两种发音都返回其实不是这个包的设计初衷，它的设计初衷是利用词库和词频返回大部分的情况，当然后续有空再考虑增加新的 API 来支持多音字的情况。

#144 的问题应该是词库版本的问题，可以直接 PR 修改 data 下的文件即可。
