### ISSUE TITLE
Error in data

### ISSUE THREAD

**Issue by cschasiepen** [overtrue/pinyin#185]
Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/vendor/overtrue/pinyin/data/words_1 on line 3

**Comment by cschasiepen** [comment]
$stadt['link'] = make_orte_url($stadt['text'], $stadt['ort_id']);

function url_to_text($output) {
        $output = trim($output);
    
           // language_id 6 == chinese
            if(language_id == 6)
            {
            echo $output;
            $pinyin = new Pinyin();
            $output = $pinyin->permalink($output);
            }

**Comment by overtrue** [comment]
what is the name of city?
