### ISSUE TITLE
保留标点不生效

### ISSUE THREAD

**Issue by NiZerin** [overtrue/pinyin#187]
输入：$pinyin->sentence('高埗镇保安围村3007-3-1', PINYIN_KEEP_PUNCTUATION);
输出：gao bu zhen bao an wei cun 300731

符号 ‘-‘ 被删除了

**Comment by NiZerin** [comment]
是我搞错了， sorry！

**Comment by NiZerin** [comment]
确实有这个 bug

**Comment by NiZerin** [comment]
已找到其他解决方案，先关闭

**Comment by jasonjiang123** [comment]
怎么解决的
