### ISSUE TITLE
安装版本要求太高，能否兼容 php 7

### ISSUE THREAD

**Issue by spendist** [overtrue/pinyin#188]
这个需要 v8.0.4  是不是有点太高要求了， 能否降低版本需求，兼容更多的使用环境。  或者写成传统的 class 类

**Comment by overtrue** [comment]
PHP 7.4 在 7 个月前就没有积极的支持了。并且安全性支持也将在4个月后结束。 还有，你也可以选择使用这个包的旧版本来兼容 PHP 7 ，比如 3.x 只需要 PHP 5.5  https://github.com/overtrue/pinyin/blob/3.x/composer.json#L28
