### ISSUE TITLE
关于 女 这个 拼音  

### ISSUE THREAD

**Issue by leeaikong** [overtrue/pinyin#191]
既然是转拼音  应该是用 nv  而不是  nyu  ，   就好像你用拼音打字输入法 输入 nyu 根本不成字 

我觉得应该改成更通用的 拼音方式  用 v 代替

**Comment by luolinlang** [comment]
旅行也不是lyu 是lv

**Comment by overtrue** [comment]
> 旅行也不是lyu 是lv

https://xbbjb.bttc.edu.cn/info/1017/1049.htm
https://www.nia.gov.cn/n741440/n741542/c1440098/content.html

**Comment by luolinlang** [comment]
lǚ lyu lv 三都行, 不过输入法确实只认lv

**Comment by overtrue** [comment]
护照姓名转换：
https://github.com/overtrue/pinyin#%E6%8A%A4%E7%85%A7%E5%A7%93%E5%90%8D%E8%BD%AC%E6%8D%A2

nv/lv/lyu/lǚ 的问题：
https://github.com/overtrue/pinyin#nvlvlyul%C7%9A-%E7%9A%84%E9%97%AE%E9%A2%98
