### ISSUE TITLE
如何转首拼或者全拼的字符串中如果是1111 四个数字开头的字符串会转换失败，报错信息和代码我放下面了

### ISSUE THREAD

**Issue by chenzhulin** [overtrue/pinyin#193]
代码行数大概在100行左右
报错信息：iconv(): Detected an illegal character in input string

$string = "1224旺仔QQ糖";
$goods_initials = (new PinYin())->getFirstPY($string);
$goods_initials_all = (new PinYin())->getAllPY($string);

var_dump($goods_initials,$goods_initials_all);

**Comment by overtrue** [comment]
你确定你用的 pinyin 库是我写的？

**Comment by overtrue** [comment]
这个 `getFirstPY ` 和 `getAllPY `  应该没有在我的这个库里存在过哈

**Comment by chenzhulin** [comment]
> Owner
哈哈哈弄错了，这个不是大佬你写的，抱歉抱歉

**Comment by chenzhulin** [comment]
但是大佬我用你这个工具包也有点问题
![image](https://user-images.githubusercontent.com/45781856/236799122-b97fc88c-45ae-479d-978d-7b899fb65686.png)

![image](https://user-images.githubusercontent.com/45781856/236799161-1d73f111-c26f-4d5f-9fa7-8ff6af7afc3d.png)

输出的内容也不对应数字没有输出

**Comment by chenzhulin** [comment]
解决了
