### ISSUE TITLE
多音字句子中的"家长"

### ISSUE THREAD

**Issue by luolinlang** [overtrue/pinyin#194]
shì
hòu
xué
sheng
hé
jiā
cháng
dào
qiàn

一句中家长的长不对怎么修正?

**Comment by luolinlang** [comment]
`require __DIR__ . '/vendor/autoload.php';

use Overtrue\Pinyin\Pinyin;

$pinyin_str = Pinyin::sentence('事后学生和家长道歉');
echo '<pre>';
print_r($pinyin_str);
echo '</pre>';
`

**Comment by overtrue** [comment]
更新版本吧，新版正常：

```bash
@overtrue ➜ ~/www/pinyin (master ✗)
$ ./bin/pinyin 事后家长和学生道歉 --method=sentence --tone-style=symbol
shì hòu jiā zhǎng hé xué sheng dào qiàn
```

**Comment by luolinlang** [comment]
👌

**Comment by luolinlang** [comment]
试了不行啊

**Comment by overtrue** [comment]
最新版是 5.1.1， `composer info overtrue/pinyin` 看看你的版本。

**Comment by luolinlang** [comment]
报错了……
composer info overtrue/pinyin


  [InvalidArgumentException]
  Package "overtrue/pinyin" not found, try using --all (-a) to show all available packages.
单独 composer info 没看到o开头的包

**Comment by overtrue** [comment]
vendor 目录下没有 overtrue/pinyin 这个目录么？

**Comment by luolinlang** [comment]
没有, 我是git下载你的项目的,还有那个
`
使用 Composer 安装:

composer require overtrue/pinyin:^5.0`
命令我这会报错: Root package 'overtrue/pinyin' cannot require itself in its composer.json

**Comment by luolinlang** [comment]
[
![image](https://github.com/overtrue/pinyin/assets/48898373/a8adac7e-b7ef-4536-9b98-ec5762d7173c)
](url)

**Comment by overtrue** [comment]
不要在我的包目录你执行这个命令…… 在你自己的项目里 composer require 😢

**Comment by overtrue** [comment]
这句英文翻译一下花不了几秒钟的

**Comment by luolinlang** [comment]
现在一会cháng一会zhǎng /_ \

**Comment by overtrue** [comment]
所以你怀疑你的电脑 CPU 在逗你玩？

**Comment by luolinlang** [comment]
![image](https://github.com/overtrue/pinyin/assets/48898373/6849da0d-42e9-4b1b-8a11-7ab8c9dae4f9)
没事了, 不说了
