### ISSUE TITLE
腾讯云自动检测会报警

### ISSUE THREAD

**Issue by hkargv** [overtrue/pinyin#196]
检测到存在待处理的恶意文件：*****/vendor/overtrue/pinyin/bin/build，威胁等级：严重，您的服务器疑似被黑客入侵，建议您及时确认，避免造成严重损失，请前往[主机安全控制台]查看详细信息

**Comment by overtrue** [comment]
那个脚本是刷新词典用的，已经排除了，更新至 5.2.1 即可。感谢反馈！

**Comment by TheNorthMemory** [comment]
https://github.com/wechatpay-apiv3/wechatpay-php/issues/87#issuecomment-1102327541

建议不用跨OS部署及采用高版本（>= 2.1.10 ) 的 composer。
