### ISSUE TITLE
腾讯管家报毒：\overtrue\pinyin\bin\build

### ISSUE THREAD

**Issue by bmkj** [overtrue/pinyin#197]
这个文件，腾讯管家报毒：\overtrue\pinyin\bin\build

应该是文件里这2个地方报毒：
`if (!file_exists($charsSouce)) {
    file_put_contents($charsSouce, file_get_contents('https://raw.githubusercontent.com/mozillazg/pinyin-data/master/pinyin.txt'));
}

if (!file_exists($wordsSouce)) {
    file_put_contents($wordsSouce, file_get_contents('https://raw.githubusercontent.com/mozillazg/phrase-pinyin-data/master/large_pinyin.txt'));
}`

**Comment by overtrue** [comment]
忽略即可

**Comment by overtrue** [comment]
这是你 clone的项目还是 composer 安装的？如果是 composer 安装的应该没有这个文件才对啊

**Comment by bmkj** [comment]
composer安装的，有这个文件的
