### ISSUE TITLE
取首字母时，能否保留完整的英文

### ISSUE THREAD

**Issue by z7z** [overtrue/pinyin#199]
我想要的结果
CGV电影院 => cgvdyy

现在我用的 Pinyin::abbr($name)->join('') 得到的是
CGV电影院 => cdyy

可能是有方法，但是我文档里没看到例子，有人指导一下吗，谢谢

**Comment by overtrue** [comment]
```php
echo Pinyin::abbr('CGV电影院', false, true)->join(''); // CGVdyy
```
