### ISSUE TITLE
曾字应该读作zeng

### ISSUE THREAD

**Issue by maverickchangithub** [overtrue/pinyin#202]
但是转化后会变成ceng。

**Comment by overtrue** [comment]
请提供上下文

**Comment by maverickchangithub** [comment]
> 请提供上下文
在laravel 项目里使用
Pinyin::sentence($author->name, 'none');
转换的所有人名都是ceng
是不是不能用sentence？

**Comment by overtrue** [comment]
看一下 readme 呗？

**Comment by maverickchangithub** [comment]
刚看到原来可以用name。谢谢。之前看的是laravel-pinyin的readme里面没有。
