### ISSUE TITLE
发现两个小bug

### ISSUE THREAD

**Issue by LiXunGuan** [overtrue/pinyin#26]
bug：
1、···only_chinese 设置为true的时候···
 `Pinyin::parse("带着希望去china");` 返回的数组里面src只有中文`带着希望去`

2、使用Pinyin::parse("带着希望去china")返回的数组`letter`英语单词只有首字母

**Comment by overtrue** [comment]
第一点是Bug，但是第二点返回的里面本来就去除了英文的。
