### ISSUE TITLE
'堃' 字无法转换为拼音

### ISSUE THREAD

**Issue by magichan** [overtrue/pinyin#28]
我在写一个用户管理系统，用户头像的存储是使用 **年级 + 中文名字的拼音** 构成的，因此调用了这个类库，但在测试时，发现 **堃** ( kun ) 字没有被转为拼音( 摔呀，这还是我自己的名字 )。
测试代码如下
```
require '../vendor/autoload.php';
use Overtrue\Pinyin\Pinyin;
Pinyin::set('delimiter','');
Pinyin::set('accent',false); // 设置 中文转拼音 类库, 无分隔，无音调

$name = '堃';
$name_pinyin = Pinyin::trans($name); // 获取拼音
echo $name_pinyin;
```
输出结果( 直接输出了原汉字 ):
![image](https://cloud.githubusercontent.com/assets/9430353/10767694/48ecdd48-7d18-11e5-93df-6172b954fb16.png)

同时测试了几个少见的字，都能够正确输出。

**Comment by overtrue** [comment]
@magichan 是词库没有这个字的原因，已经补充，请更新到 2.6.3 版本

```sh
composer update overtrue/pinyin
```
