### ISSUE TITLE
内存性能优化~

### ISSUE THREAD

**Issue by medz** [overtrue/pinyin#37]
看了下源码~将3.5MB的库都载入到内存中使用~造出了极大的性能浪费~
优化方案可以使用文件流打开库文件~对行操作进行匹配读取~虽然速度没有直接在数组中操作快~
但是可以避免性能浪费~建议加入缓存拓展接口~因为第三方使用的项目都有自己的缓存机制~加一个save和get的接口~可以加快转换~
在实际项目中~载入3.5MB的文件（还在不断扩大）真的不现实。
可能稍微不注意就内存溢出了！

**Comment by Xiphin** [comment]
赞同

**Comment by lihaitao1** [comment]
速度好慢，差一个词要3s以上

**Comment by overtrue** [comment]
@lihaitao1 你哪个词？我转换的结果：

2300 个常用单字，107089 条词汇（成语，俗语）：

```
2300 Single chars time usage: 0.99953603744507
107089 Dictionary chars time usage: 5.3670089244843
Total timeusage: 6.3755459785461
```

**Comment by lihaitao1** [comment]
@overtrue  普通任何一个字我都要2s以上，你append（list）就要1.56s，然后查词，就要1s多

**Comment by overtrue** [comment]
@lihaitao1 这就奇怪了，我让几个朋友试了都是 0.0x 范围。

**Comment by lihaitao1** [comment]
@overtrue 额，我是直接new Pinyin（）导致的吗？但是也不应该啊。

**Comment by overtrue** [comment]
@lihaitao1 不应该，不过我也没有文档介绍 `new Pinyin()` 的用法。

**Comment by medz** [comment]
@overtrue 不在于速度~而在于~如果用于生产环境下~载入内存过大~亲测~

**Comment by overtrue** [comment]
@medz 3M也算大？

**Comment by medz** [comment]
@overtrue 如果你是作为cli编程，当然不算~但是，用于线上，你觉得不大？再加上php的后端运行不是 异步~也就是说~如果有请求进来~就需要读取到内存占用一次~而php的默认设置是2m~很多虚拟机也是比较低的~如果我们抛开虚拟机~讲主机，一个请求耗费3m内存，也是不小的开销了~虽然这是硬件可以解决的~
但是哥，我的重点不是内存多大~而是，我只是觉得可以提供更多数据读取方式的接口~举了例子~你是读到数组的~读取数组的方法支持其他方法的注入~外部别人用的时候想用缓存或者其他~可以按照规定要求的get和set接口进行编写~其实set不难吧？key，value，get方式传递key，返回get，这样也方便集成~一直想在产品里面用这个的~就是因为这个问题~一直没用！！

**Comment by overtrue** [comment]
@medz 你可以按你的想法做一下实验就知道了，不过我正在构思下一个版本，你的建议我也会加进来。下一个版本应该会数据小很多，然后接口会更方便。:smile: ，这也是我一直没有对这个 issue 有动作的原因。

**Comment by medz** [comment]
@overtrue 好的~只是一直没时间~我只想想fork一份改成这样的~·工作上的事情，无力分身~

**Comment by overtrue** [comment]
@medz 嗯啦

**Comment by Xiphin** [comment]
期待下一版

**Comment by overtrue** [comment]
@Xiphin @medz @lihaitao1 欢迎各位试用v3: `composer require "overtrue/pinyin:v3.x-dev"` 😄

**Comment by medz** [comment]
@overtrue 好的~

**Comment by lihaitao1** [comment]
@overtrue 谢谢

**Comment by Xiphin** [comment]
@overtrue 谢谢
