### ISSUE TITLE
性能优化

### ISSUE THREAD

**Issue by brittyu** [overtrue/pinyin#43]
读了下超哥的代码，看到每次在载入词库的时候都会重新组织一下数组的数据结构（词的第一个字为键值），这个过程不知道能不能在dict.php文件中就做好，以后就不需要每次组织一下这个数据结构呢，我修改了一下代码发现在我的自己上找一个词需要1.0x秒，但是如果先组织号数据结构之后就变成了0.46x秒了。不知道这样子编写有什么原因呢？

**Comment by overtrue** [comment]
@brittyu 哈哈，其实原先是为了便于别人阅读与添加，加之也没对性能做很多方式的性能测试。所以导致了现在的样子。

我最近在做重构，可以看 https://github.com/overtrue/pinyin/tree/v2 查看进度。

**Comment by overtrue** [comment]
@brittyu 欢迎试用v3: composer require "overtrue/pinyin:v3.x-dev", 文档：https://github.com/overtrue/pinyin/tree/v3

**Comment by brittyu** [comment]
@overtrue 多谢超哥，希望能为这个项目也做点共享:P

**Comment by overtrue** [comment]
@brittyu 欢迎
