### ISSUE TITLE
v3不好扩展到Thinkphp 3.2.3中

### ISSUE THREAD

**Issue by hulang** [overtrue/pinyin#46]
v2挺好扩展的。把：namespace Overtrue\Pinyin;命名空间注释。就扩展成功了。

今天看到老大更新到v3了。。扩展的试了下。
提示：Pinyin.php   164行错误。
namespace Overtrue\Pinyin;命名空间我注释了。不注释貌似不好扩展。

**Comment by overtrue** [comment]
@hulang 

1. 使用 composer 安装
2. 不要注释命名空间
3. 正确的使用（按文档）
