### ISSUE TITLE
数据使用通用的格式好方便其他语言实现？

### ISSUE THREAD

**Issue by zhuangya** [overtrue/pinyin#50]
比如有没有考虑过类似 json 或者 yaml 的格式来表示数据
这样其他的语言也可以读过来分别做实现

**Comment by overtrue** [comment]
其实有测试过很多方案啦，后来选择了这种空间换时间的方式。毕竟其它格式后转成php数据耗时较长。

**Comment by zhuangya** [comment]
开发的时候用交换格式，发布到包管理器的时候预编译一遍这样呢？

**Comment by overtrue** [comment]
@zhuangya 其实词典这个东西变化少，我的源文件在 [tools/sources](https://github.com/overtrue/pinyin/tree/master/tools/sources) 下，我是用工具生成 data 目录下的数据的，所以其实 data 下的内容已经算是预编译了吧 😄 ，我也说明了如果要贡献词典补丁在 tools 下修改。

**Comment by zhuangya** [comment]
@overtrue 原来如此，我来研究一下好了。
看看有没有可能实现一个其他语言的版本。
closing this 👍

**Comment by overtrue** [comment]
@zhuangya 我收集了一些，你看看：https://github.com/overtrue/pinyin-resources
