### ISSUE TITLE
更新 sae 版本

### ISSUE THREAD

**Issue by zhuangya** [overtrue/pinyin#52]
我看到 [这里](https://github.com/overtrue/pinyin/blob/8d98a29b7d983dcb5ebf3f741dd57b301fb43513/data/surnames#L70) 是有 盖 这个姓的 但是访问

http://string2pinyin.sinaapp.com/?str=%E7%9B%96%E5%B0%8F%E5%A7%90

却返回的是 ge3

因为 sae 的版本比较老？

**Comment by overtrue** [comment]
@zhuangya 哈哈，差点忘记了，还真是没更新呢

**Comment by overtrue** [comment]
@zhuangya 同步了不过 PHP 5.3 有一个 bug，目前我手里没有 PHP 5.3 还没找到。晚点我再来解决。

**Comment by overtrue** [comment]
@zhuangya 找到问题所在了：

[mb_substr](http://php.net/manual/en/function.mb-substr.php) 的第3个参数 `length` 在 PHP < 5.4 的时候传 `null` 代表 0，5.4+ 代表不限制，截取到最后，所以旧的写法在 5.3 下转换后只剩下一个姓了：

```diff
- $string = $pinyin . mb_substr($string, mb_strlen($surname, 'UTF-8'), null, 'UTF-8');
+ $string = $pinyin . mb_substr($string, mb_strlen($surname, 'UTF-8'), mb_strlen($string, 'UTF-8') - 1, 'UTF-8');
```

**Comment by zhuangya** [comment]
可是 sae 还是有问题的版本 😕

**Comment by overtrue** [comment]
@zhuangya 啥问题？

**Comment by zhuangya** [comment]
```❯ http http://string2pinyin.sinaapp.com/\?str\=%E7%9B%96%E5%B0%8F%E5%A7%90
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json;charset:utf-8
Date: Sun, 22 May 2016 03:44:06 GMT
Server: nginx
Transfer-Encoding: chunked
Via: 10.67.15.22
X-Time-usage: 0.0897340774536

{
    "result": [
        "gai",
        "xiao",
        "jie"
    ],
    "status": "T",
    "str": "盖小姐"
}```

这里应该是 `ge xiao jie` 才对呀

**Comment by overtrue** [comment]
@zhuangya 

http://string2pinyin.sinaapp.com/?str=%E7%9B%96%E5%B0%8F%E5%A7%90&api=name

**Comment by overtrue** [comment]
@zhuangya http://string2pinyin.sinaapp.com/doc.php

**Comment by zhuangya** [comment]
原来是这样

  

thanks

On 5月 22 2016, at 11:48 中午, 安正超 &lt;notifications@github.com&gt; wrote:  

> [@zhuangya](https://github.com/zhuangya)
<http://string2pinyin.sinaapp.com/doc.php>

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/overtru
e/pinyin/issues/52#issuecomment-220812726)![](https://github.com/notifications
/beacon/AAedXo2nYHBZ8XC91m8ydnkXZpTqNT2iks5qD9IMgaJpZM4Ih5fY.gif)

**Comment by overtrue** [comment]
@zhuangya 😄
