### ISSUE TITLE
词库里面一些多音字拼音会选取较生僻读音

### ISSUE THREAD

**Issue by ihipop** [overtrue/pinyin#63]
[沈阳](http://string2pinyin.sinaapp.com/?accent=0&str=%E6%B2%88%E9%98%B3)
沈日常使用基本只有`shěn`一个读音，`chén`作为通假字，在现代汉语中基本上没有使用
词库里面这些常用词语，还需要进行优化

**Comment by overtrue** [comment]
Thanks.
