### ISSUE TITLE
自定义词库中有些汉字无法转译成拼音字母

### ISSUE THREAD

**Issue by finalxcode** [overtrue/pinyin#65]
你好，我在pinyin/data目录下新增了自定义的文件words_6，文件内容如下：
﻿<?php 
 return array (
  '' => '    zē',
  '' => '    gē',
  '隣' => '    lē',
);
但是输出$pinyin = $pinyin->convert('')的返回值，确是个空数组。通过查看源代码，发现你首先对字符串进行了预处理，如果不满足正则匹配preg_replace("~[^\p{Han}\p{P}\p{Z}\p{M}\p{N}\p{L}\t]~u", '', $string)就返回空字符串，难道“”不满足p{Han}这个匹配条件吗？是否可以提供一个有效的p{Han}所支持的字符列表？如果p{Han}所对应的汉字范围不支持，是否有方法修正这样的错误？谢谢~

**Comment by overtrue** [comment]
@finalxcode 建议按我 README 说的方法来添加自定义，以便于帮助更多的人

**Comment by xFelino** [comment]
@finalxcode 「」与「」为统一码私用区域的汉字，不建议添加至data 中。而「隣」U+F9F1 同「隣」U+96A3，通常前者都不应该出现，亦不建议添加。

**Comment by finalxcode** [comment]
谢谢

2016-10-22 0:17 GMT+08:00 xFelino <notifications@github.com>:
