### ISSUE TITLE
preg_replace("~[^\p{Han}\p{P}\p{Z}\p{M}\p{N}\p{L}\t]~u", '', $string)

### ISSUE THREAD

**Issue by JihanZhuang** [overtrue/pinyin#66]
In the pinyin.php file,I have a question about the code.
preg_replace("~[^\p{Han}\p{P}\p{Z}\p{M}\p{N}\p{L}\t]~u", '', $string)

Pay attention to the ^ character,Is it right?what does the code means?

**Comment by overtrue** [comment]
`^` in `[]`, Match a single character not present in the list`[]`:

```php
/[^abc]/ => match a single character not present in [a, b, c] 
```

**Comment by overtrue** [comment]
https://regex101.com/r/l0YU7H/1

**Comment by JihanZhuang** [comment]
oh,thank you.
