### ISSUE TITLE
对于非汉字的部分不想处理，希望保持原样该怎样设置？

### ISSUE THREAD

**Issue by amazesam** [overtrue/pinyin#77]
你好，我想请教一下，对于非汉字的部分不想处理，希望保持原样该怎样设置？

**Comment by overtrue** [comment]
sentence 方法本来就会保留非中文的字符啊，除了符号：

http://string2pinyin.sinaapp.com/?api=sentence&str=%E6%B5%8B%E8%AF%95abc123%E5%8A%A0%E4%B8%8A%E4%B8%AD%E6%96%87
