### ISSUE TITLE
地区名称多音字有座处理么？

### ISSUE THREAD

**Issue by sxdubin** [overtrue/pinyin#80]
想问一下作者，地区多音字这边是怎么处理的？例如：长春(changchun)(zhangchun)  重庆(chongqing zhongqing)

**Comment by overtrue** [comment]
@sxdubin 所以你是想问原理还是在问这个包是否支持？

**Comment by sxdubin** [comment]
这边看到了在words_1这个文件里许多地名都做了白名单处理。

**Comment by overtrue** [comment]
@sxdubin 嗯，多音字原理有在这里说明：https://github.com/overtrue/pinyin-resources
