### ISSUE TITLE
几个地名翻译错误

### ISSUE THREAD

**Issue by ymind** [overtrue/pinyin#82]
1. 乌拉特前旗，翻译为`wù l tè qián qí`，应为`wù lā tè qián qí`；
2. 朝阳区，翻译为`zhāo yáng qū`，应为`cháo yáng qū`；
3. 绩溪县，翻译为`jī xī xiàn`，应为`jì xī xiàn`；
4. 百色县，翻译为`bó sè shì`，应为`bǎi sè shì`；
5. 都安瑶族自治县，翻译为`dōu ān yáo zú zì zhì xiàn`，应为`dū ān yáo zú zì zhì xiàn`；
6. 塔什库尔干，翻译为`tǎ shén kù ěr gàn`，应为`tǎ shí kù ěr gān`；
7. 长阳土家族自治县，翻译为`zhǎng yáng tǔ jiā zú zì zhì xiàn`，应为`cháng yáng tǔ jiā zú zì zhì xiàn`；
8. 马尾区，翻译为`mǎ yǐ qū`，应为`mǎ wěi qū`；
9. 三都水族自治县，翻译为`sān dōu shuǐ zú zì zhì xiàn`，应为`sān dū shuǐ zú zì zhì xiàn`；

**Comment by overtrue** [comment]
@ymind 感谢反馈，麻烦加到这里：https://github.com/overtrue/pinyin-dictionary-maker/blob/master/patches/words.txt

**Comment by ymind** [comment]
感谢回复！

不过，其中的“乌拉特”在翻译后为`wù l tè`，丢失了韵母“ā”，这应该不是词库问题造成的。
