### ISSUE TITLE
能否批量取姓名的拼音呢？

### ISSUE THREAD

**Issue by leave01** [overtrue/pinyin#87]
作者你好
现在有个情况是我有1000条记录，存放了中文名，我想要取出这些人名的拼音，但是透过`$pinyin->name()`这样遍历去取会花费超过10s的时间，我将这些姓名变成一个大的文本想直接透过`$pinyin->name()`一下子得到姓名，但我失败了，我得到了第一个字的拼音。
那么请问有什么更好的办法可以解决这个问题吗？

非常感谢！

**Comment by overtrue** [comment]
@leave01 所以你是每次都去现转拼音？就不能先把这1000条记录的拼音转完存起来再查？

**Comment by leave01** [comment]
Okay!
看来我有点糊涂了，感谢提醒！
