### ISSUE TITLE
有没有中文取首字母，英文或数字保留的选项

### ISSUE THREAD

**Issue by ebsinori** [overtrue/pinyin#91]
在中英文混合的字符串里全部取首字母感觉比较奇怪，特别是带数字的时候，比如“测试123test”，转换后只剩“cs1”了，意义都不太一样了。考虑加这功能吗？

**Comment by overtrue** [comment]
业务场景是？

**Comment by ebsinori** [comment]
就是搜索啊，比如我要按首字母搜“测试10”的内容，如果按现在这个功能，数据库只能存“cs1”，但用户搜可能是搜“cs10”，匹不上了。

**Comment by overtrue** [comment]
这样做搜索有点坑哦，建议使用 sphinx 等来做，这个功能我后面加上。

**Comment by ebsinori** [comment]
主要是前期业务场景不太复杂，所以想直接在sql里面搜索，这样实现起来快一点。全文检索我们之后也会考虑加上，谢谢你的建议。

**Comment by helloMJW** [comment]
现在我们这儿也有这个需求要取首字母的，业务场景是 将中文拼音前首字母作为用户账户…………
这个取首字母实现了？

**Comment by overtrue** [comment]
@helloMJW 所以你都没看文档就来问了么？文档上不是有例子么？

**Comment by chenhaizano** [comment]
中文取首字母，英文或数字保留

+1

**Comment by jafu2000** [comment]
在 pinyin.php 文件加上

``
 /**
     * Return first letters,中文取首字母，保留英文字母和数字并全部转为大写字母.
     *
     * @param string $string
     * @param string $delimiter
     *
     * @return string
     */

    public function to_big_abbr($str, $delimiter = '')
    {
        $pinyin = app(Pinyin::class);
        return strtoupper(implode($delimiter, array_map(function ($pinyin) {
            $first = $pinyin[0];
            if (preg_match('/[A-Z0-9]/', $pinyin)) {
                $first = $pinyin;
            }
            return $first;
        }, $pinyin->convert($str, false))));
    }
``

**Comment by ebsinori** [comment]
@jafu2000 你这个只有单词中包含大写字母才行

**Comment by judithhuang** [comment]
@overtrue 能贴下文档上的例子吗？我也没有找到

**Comment by kaiweispacebib** [comment]
# 获取首字符字符串
```
$pinyin->abbr('带着希望去旅行'); // dzxwqlx
$pinyin->abbr('带着希望去旅行', '-'); // d-z-x-w-q-l-x
```

**Comment by dannyZhou** [comment]
https://github.com/overtrue/pinyin/issues/91#issuecomment-307704230

使用场景： 智能电视搜索资源 一般采用 汉字首字母搜索，例如 `小黄人 -> xhr`

但是如果是 `小黄人2017新版` 呢？  `xhr2017xb` or `xhr2xb`

**Comment by Sanstones** [comment]
我想知道能同时保留数字和英文吗，比如"你好啊 2019 哈哈哈 Xf" => nihaoa2019hahahaxf

**Comment by overtrue** [comment]
```php
use Overtrue\Pinyin\Pinyin;

$pinyin = new Pinyin();

echo $pinyin->sentence('你好啊 2019 哈哈哈 Xf', '', PINYIN_KEEP_NUMBER | PINYIN_KEEP_ENGLISH);

//输出：nihaoa2019hahahaXf
```

**Comment by Sanstones** [comment]
了解 谢谢

**Comment by zhanqixuan** [comment]
用过了，转得确实很准确，但是性能差点，上万或上几十万条就比较慢了
