### ISSUE TITLE
拼音转换错误

### ISSUE THREAD

**Issue by lengyuan** [overtrue/pinyin#96]
请看例句
还说**什么**呢？还给你。**还**个屁！
这句话转换的拼音为
hái shuō shí mǒ ne? huán gěi nǐ. hái gè pì

词语”什么“的拼音转换错误有些奇怪。
我看在CEDICT里面是有”什么“这个词条的
什麼 什么 [shen2 me5] /what?/who?/something/anything/
但是在words_*文件里面却没有找到”什么“

另外，对于单个多音字，比如例子里面第二个还字，现在只是依照在word_*文件里面的出现顺序来获取拼音。有考虑使用词性吗？

谢谢

**Comment by overtrue** [comment]
@lengyuan 这个库的转换是简单的按长度优先匹配的，多音字部分按使用词频优先，无法做到完整覆盖，不过 "什么" 翻译为 `shí mǒ` 是有问题的，这个应该是能解决，不过 `还个屁` 这个就无法识别出它是 `huan` 还是 `hai` 了

**Comment by lengyuan** [comment]
什么 这个应该是在你生成的词库里面漏掉了。
感觉单个的多音字还得按照词性，或者是穷举所有的组合。

**Comment by overtrue** [comment]
@lengyuan 嗯，所以我说它是 bug 嘛，最后那个 “还什么” 必须得结合上下文，否则，它可以读两个音都没问题，但是这个很难做到，起码现在的代码是无法做到语义分析的。
