### ISSUE TITLE
非常棒的工具，能再科普一下跟intl的实现有什么异同吗？

### ISSUE THREAD

**Issue by yanhuixie** [overtrue/pinyin#98]
rt，比如intl的transliterator_transliterate，也能实现对汉字到拼音的转换，但我不知道它背后是不是使用dictionary来实现的。

**Comment by overtrue** [comment]
intl 应该是用单字词典吧，在多音字处理上可能会有问题

**Comment by yanhuixie** [comment]
明白了，谢谢。确认了一下intl是基于 International Components for Unicode 实现的，从实例来看确实处理不了多音字。
